"""Manifest of stored blobs — the durable index of what `storage` wrote, for both
run-scoped and org-scoped files. One global table (Postgres `public.blobs` when
SF_DB=postgres, else a sqlite file), mirroring the users/organizations directory.

A row is metadata only (scope, scope_id, kind, storage_key, content_type, size, sha256);
the bytes live in Supabase Storage (or the local fallback) addressed by `storage_key`.
"""
from __future__ import annotations

import os
import sqlite3
import time

from . import dbshim


class BlobStore:
    def __init__(self, sqlite_path: str):
        self._pg = (os.environ.get("SF_DB") or "").lower() == "postgres"
        self._sqlite_path = sqlite_path
        self._ensure()

    def _ensure(self) -> None:
        if self._pg:
            conn = dbshim._pg_connect(os.environ["DATABASE_URL"])
            try:
                with conn.transaction():
                    conn.cursor().execute(
                        "CREATE TABLE IF NOT EXISTS public.blobs ("
                        "id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "
                        "scope text NOT NULL, scope_id text NOT NULL, kind text, "
                        "storage_key text NOT NULL, content_type text, size_bytes integer, "
                        "sha256 text, created_at timestamptz DEFAULT now())")
            finally:
                conn.close()
        else:
            os.makedirs(os.path.dirname(self._sqlite_path) or ".", exist_ok=True)
            c = sqlite3.connect(self._sqlite_path)
            c.execute("CREATE TABLE IF NOT EXISTS blobs ("
                      "id INTEGER PRIMARY KEY AUTOINCREMENT, scope TEXT NOT NULL, "
                      "scope_id TEXT NOT NULL, kind TEXT, storage_key TEXT NOT NULL, "
                      "content_type TEXT, size_bytes INTEGER, sha256 TEXT, created_at REAL)")
            c.commit(); c.close()

    def record(self, scope: str, scope_id: str, storage_key: str, *, kind: str | None = None,
               content_type: str | None = None, size_bytes: int | None = None,
               sha256: str | None = None) -> None:
        """Record one stored blob. `scope` is 'run' or 'org'."""
        if scope not in ("run", "org"):
            raise ValueError(f"blob scope must be 'run' or 'org', got {scope!r}")
        sql = ("INSERT INTO blobs (scope, scope_id, kind, storage_key, content_type, "
               "size_bytes, sha256, created_at) VALUES (?,?,?,?,?,?,?,?)")
        params = (scope, scope_id, kind, storage_key, content_type, size_bytes, sha256, time.time())
        if self._pg:
            conn = dbshim._pg_connect(os.environ["DATABASE_URL"])
            try:
                with conn.transaction():
                    conn.cursor().execute(sql.replace("?", "%s"), params)
            finally:
                conn.close()
        else:
            c = sqlite3.connect(self._sqlite_path)
            c.execute(sql, params); c.commit(); c.close()

    def list_for(self, scope: str, scope_id: str) -> list[dict]:
        sql = ("SELECT scope, scope_id, kind, storage_key, content_type, size_bytes, sha256 "
               "FROM blobs WHERE scope=? AND scope_id=? ORDER BY id")
        if self._pg:
            conn = dbshim._pg_connect(os.environ["DATABASE_URL"])
            try:
                with conn.transaction():
                    cur = conn.cursor()
                    cur.execute(sql.replace("?", "%s"), (scope, scope_id))
                    return [dict(r) for r in cur.fetchall()]
            finally:
                conn.close()
        c = sqlite3.connect(self._sqlite_path); c.row_factory = sqlite3.Row
        try:
            return [dict(r) for r in c.execute(sql, (scope, scope_id)).fetchall()]
        finally:
            c.close()
