"""One connect() seam selecting sqlite (default) or Postgres for the per-run stores.

SF_DB unset/`sqlite` -> plain sqlite3, byte-identical to today (the hermetic test
guarantee). SF_DB=postgres -> a thin wrapper over psycopg3 against DATABASE_URL
(the Supabase transaction pooler on 6543), with:

  - one Postgres SCHEMA per run (`sf_run_<sanitized run_id>` from the path's dirname) —
    every store SQL string stays as-is except placeholder translation;
  - `SET LOCAL search_path` inside a transaction per statement — the 6543 pooler is
    transaction-mode, session `SET` does NOT survive across statements;
  - a `public.sf_runs` registry row (ON CONFLICT DO NOTHING) for pg-side run discovery;
  - `?`->`%s`, sqlite DDL deltas (AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY,
    REAL -> double precision), `.lastrowid` via appended `RETURNING id`;
  - 3x retry with backoff (network writes can fail where local sqlite couldn't).

The run DIRECTORY is still created in pg mode — it hosts run.log/chat.jsonl (the
volume stays mandatory; only run STATE moves to Postgres).
"""
from __future__ import annotations

import os
import re
import sqlite3
import time

from . import env

_RETRY_SLEEP = 0.5
_TRIES = 3
# Tables with an `id INTEGER ... IDENTITY` column — INSERTs get RETURNING id so the
# cursor's .lastrowid keeps working (runstate/gates/agents key on natural PKs instead).
_ID_TABLES = ("tickets", "phases", "artifacts", "blockers", "verifications")


def connect(path: str):
    if env.db_backend() != "postgres":
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        conn = sqlite3.connect(path)
        conn.row_factory = sqlite3.Row
        return conn
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)  # run.log/chat.jsonl live here
    run_id = os.path.basename(os.path.dirname(path))
    return PgConn(_pg_connect(os.environ["DATABASE_URL"]), run_id)


def _pg_connect(url: str):
    import psycopg
    from psycopg.rows import dict_row

    conn = psycopg.connect(url, row_factory=dict_row, autocommit=True)
    # psycopg3 auto-prepare breaks under transaction pooling (prepared stmts are
    # per-backend; the pooler swaps backends under us).
    conn.prepare_threshold = None
    return conn


def registry_runs() -> list:
    """Runs known to the pg `public.sf_runs` registry: [{run_id, created}] — [] on the
    sqlite backend (discovery stays directory-based) and on any pg error (the volume
    listing must keep working even if the registry is briefly unreachable)."""
    if env.db_backend() != "postgres":
        return []
    try:
        conn = _pg_connect(os.environ["DATABASE_URL"])
        try:
            with conn.transaction():
                cur = conn.cursor()
                cur.execute(
                    "SELECT run_id, extract(epoch from created_at) AS created "
                    "FROM public.sf_runs")
                return list(cur.fetchall())
        finally:
            conn.close()
    except Exception:
        return []


def schema_for(run_id: str) -> str:
    base = run_id[4:] if run_id.startswith("run-") else run_id
    return "sf_run_" + re.sub(r"[^a-z0-9_]", "_", base.lower())


# Path/shell junk that can never be a legitimate run id (a wrong db-CLI arg order once
# landed values like "/data/runs" in the run_id slot). Defense in depth: refuse to
# CREATE SCHEMA for these even if a caller bypasses the CLI guard. Kept deliberately
# narrow (separators/whitespace/empty) so real sanitization cases like "run-AB.C-9"
# still create their schema.
def _is_malformed_run_id(run_id: str) -> bool:
    return (not run_id) or bool(re.search(r"[/\\\s]", run_id))


def _translate(sql: str) -> str:
    sql = sql.replace("?", "%s")
    sql = sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT",
                      "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY")
    sql = re.sub(r"\bREAL\b", "double precision", sql)
    return sql


class _Cursor:
    """Result holder: psycopg buffers rows client-side at execute, so fetches stay
    valid after the statement's transaction closes."""

    def __init__(self, rows, rowcount, lastrowid):
        self._rows = list(rows)
        self.rowcount = rowcount
        self.lastrowid = lastrowid

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return self._rows


class PgConn:
    def __init__(self, conn, run_id: str):
        self._conn = conn
        self._run_id = run_id
        self._schema = schema_for(run_id)
        self._ready = False

    # -- the sqlite3.Connection surface the stores actually use ------------------------

    def execute(self, sql: str, params=()):  # noqa: C901 — one seam, kept together
        self._ensure()
        tsql = _translate(sql)
        head = tsql.lstrip().upper()
        returning = None
        if head.startswith("INSERT") and "RETURNING" not in head:
            m = re.match(r"\s*INSERT\s+INTO\s+(\w+)", tsql, re.I)
            if m and m.group(1).lower() in _ID_TABLES:
                tsql += " RETURNING id"
                returning = "id"
        wants_rows = returning or head.startswith("SELECT") or " RETURNING " in head
        return self._tx(tsql, tuple(params), wants_rows, returning)

    def executescript(self, script: str):
        self._ensure()
        stmts = [s.strip() for s in script.split(";") if s.strip()]
        last = None
        for s in stmts:
            last = self._tx(_translate(s), (), False, None)
        return last

    def commit(self):  # every statement is its own transaction
        pass

    def close(self):
        self._conn.close()

    # -- internals ----------------------------------------------------------------------

    def _tx(self, sql: str, params: tuple, wants_rows: bool, returning):
        last_err = None
        for attempt in range(_TRIES):
            try:
                with self._conn.transaction():
                    cur = self._conn.cursor()
                    cur.execute(f'SET LOCAL search_path TO "{self._schema}", public')
                    cur.execute(sql, params)
                    rows = cur.fetchall() if wants_rows else []
                    lastrowid = (rows[0] or {}).get("id") if returning and rows else None
                    return _Cursor(rows, cur.rowcount, lastrowid)
            except Exception as e:  # pooler hiccup / transient network — retry, then surface
                last_err = e
                time.sleep(_RETRY_SLEEP * (attempt + 1))
        raise last_err

    def _ensure(self):
        """Create the run's schema + registry row once per connection. Advisory-locked:
        concurrent db-CLI writers race CREATE SCHEMA on a brand-new run.

        Only factory-shaped ids (run-XXXXXXXX) REGISTER in public.sf_runs: a stray local
        process pointed at the prod DATABASE_URL once registered 53 junk "runs"
        (\"guestbook-builder\", \"deploy\", …) that the deployed console then listed —
        discovery trusts the registry, so the registry only accepts real run ids. The
        schema itself is still created (refusing the write would lose data instead)."""
        if self._ready:
            return
        if _is_malformed_run_id(self._run_id):
            raise ValueError(
                f"refusing to create a pg schema for malformed run id {self._run_id!r} "
                "(looks like a path/shell fragment, not a run id)")
        last_err = None
        for attempt in range(_TRIES):
            try:
                with self._conn.transaction():
                    cur = self._conn.cursor()
                    cur.execute("SELECT pg_advisory_xact_lock(hashtext(%s))", (self._schema,))
                    cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{self._schema}"')
                    cur.execute(
                        "CREATE TABLE IF NOT EXISTS public.sf_runs ("
                        "run_id text PRIMARY KEY, schema_name text NOT NULL, "
                        "created_at timestamptz NOT NULL DEFAULT now())")
                    if re.fullmatch(r"run-[0-9a-f]{8}", self._run_id):
                        cur.execute(
                            "INSERT INTO public.sf_runs (run_id, schema_name) VALUES (%s, %s) "
                            "ON CONFLICT DO NOTHING", (self._run_id, self._schema))
                        # Stamp this new per-run schema at the current per-run template version so
                        # the Alembic fan-out (software_factory.migrate) skips it. Best-effort: the
                        # version registry may not exist yet on a never-migrated DB.
                        from .schema_ddl import per_run_head
                        cur.execute(
                            "CREATE TABLE IF NOT EXISTS public.sf_run_schema_version ("
                            "run_id text PRIMARY KEY, version text NOT NULL, "
                            "updated_at timestamptz NOT NULL DEFAULT now())")
                        cur.execute(
                            "INSERT INTO public.sf_run_schema_version (run_id, version) "
                            "VALUES (%s, %s) ON CONFLICT (run_id) DO NOTHING",
                            (self._run_id, per_run_head()))
                self._ready = True
                return
            except Exception as e:
                last_err = e
                time.sleep(_RETRY_SLEEP * (attempt + 1))
        raise last_err
