"""dbshim: one connect() seam selecting sqlite (default — tests/fallback, byte-identical to
today) or Postgres (SF_DB=postgres + DATABASE_URL; Supabase transaction pooler on 6543).

The pg path is tested against a FAKE psycopg connection — no live database in unit tests.
"""
import os
import sqlite3

import pytest

from software_factory import dbshim


# ---------- sqlite passthrough (the hermetic guarantee) ----------

def test_default_is_plain_sqlite(tmp_path, monkeypatch):
    monkeypatch.delenv("SF_DB", raising=False)
    conn = dbshim.connect(str(tmp_path / "run-x" / "run.db"))
    assert isinstance(conn, sqlite3.Connection)
    conn.execute("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)")
    cur = conn.execute("INSERT INTO t (v) VALUES (?)", ("a",))
    assert cur.lastrowid == 1
    row = conn.execute("SELECT * FROM t WHERE v = ?", ("a",)).fetchone()
    assert row["v"] == "a"                       # row_factory=Row preserved


def test_sqlite_when_sf_db_says_sqlite(tmp_path, monkeypatch):
    monkeypatch.setenv("SF_DB", "sqlite")
    assert isinstance(dbshim.connect(str(tmp_path / "run.db")), sqlite3.Connection)


# ---------- pg translation (fake connection; no live pg) ----------

class FakeCursor:
    def __init__(self, log):
        self.log = log
        self.rowcount = 1
        self._rows = []

    def execute(self, sql, params=None):
        self.log.append((sql.strip(), tuple(params or ())))
        if "RETURNING id" in sql:
            self._rows = [{"id": 7}]
        return self

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return self._rows

    def close(self):
        pass


class FakeTx:
    def __init__(self, conn): self.conn = conn
    def __enter__(self): self.conn.tx_count += 1; return self
    def __exit__(self, *a): return False


class FakePgConn:
    def __init__(self):
        self.statements = []
        self.tx_count = 0
        self.closed = False

    def cursor(self):
        return FakeCursor(self.statements)

    def transaction(self):
        return FakeTx(self)

    def commit(self):
        pass

    def close(self):
        self.closed = True


@pytest.fixture()
def pg(monkeypatch, tmp_path):
    monkeypatch.setenv("SF_DB", "postgres")
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@pooler:6543/postgres")
    fake = FakePgConn()
    monkeypatch.setattr(dbshim, "_pg_connect", lambda url: fake)
    conn = dbshim.connect(str(tmp_path / "run-abc12345" / "run.db"))
    return conn, fake


def test_pg_derives_schema_from_path_and_sets_local_search_path(pg):
    conn, fake = pg
    conn.execute("SELECT * FROM phases WHERE name = ?", ("build",))
    sqls = [s for s, _ in fake.statements]
    assert any("SET LOCAL search_path" in s and "sf_run_abc12345" in s for s in sqls)
    assert any("FROM phases WHERE name = %s" in s for s in sqls)   # ?->%s
    assert fake.tx_count >= 1                                       # every stmt inside a tx


def test_pg_lastrowid_via_returning(pg):
    conn, fake = pg
    cur = conn.execute("INSERT INTO tickets (title) VALUES (?)", ("t",))
    assert cur.lastrowid == 7
    assert any("RETURNING id" in s for s, _ in fake.statements)


def test_pg_executescript_runs_translated_statements(pg):
    conn, fake = pg
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS a (id INTEGER PRIMARY KEY AUTOINCREMENT, ts REAL NOT NULL);
        CREATE TABLE IF NOT EXISTS b (n TEXT);
    """)
    sqls = [s for s, _ in fake.statements]
    assert any("GENERATED BY DEFAULT AS IDENTITY" in s for s in sqls)   # AUTOINCREMENT translated
    assert any("double precision" in s for s in sqls)                   # REAL translated
    assert not any("AUTOINCREMENT" in s for s in sqls)


def test_pg_write_retries_then_raises(monkeypatch, tmp_path):
    monkeypatch.setenv("SF_DB", "postgres")
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@pooler:6543/postgres")
    attempts = []

    class Boom(FakePgConn):
        def transaction(self):
            attempts.append(1)
            raise ConnectionError("pooler hiccup")

    monkeypatch.setattr(dbshim, "_pg_connect", lambda url: Boom())
    monkeypatch.setattr(dbshim, "_RETRY_SLEEP", 0)
    conn = dbshim.connect(str(tmp_path / "run-r" / "run.db"))
    with pytest.raises(ConnectionError):
        conn.execute("INSERT INTO phases (name) VALUES (?)", ("x",))
    assert len(attempts) == 3                                          # 3 tries, then surface


def test_schema_name_sanitized(monkeypatch, tmp_path):
    monkeypatch.setenv("SF_DB", "postgres")
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@x:6543/postgres")
    fake = FakePgConn()
    monkeypatch.setattr(dbshim, "_pg_connect", lambda url: fake)
    conn = dbshim.connect(str(tmp_path / "run-AB.C-9" / "run.db"))
    conn.execute("SELECT 1")
    assert any('sf_run_ab_c_9' in s for s, _ in fake.statements)       # [a-z0-9_] only


def test_registry_rejects_non_factory_run_ids(monkeypatch, tmp_path):
    # A stray local process pointed at prod once registered 53 junk "runs" — only
    # run-XXXXXXXX ids may land in public.sf_runs (the schema is still created).
    monkeypatch.setenv("SF_DB", "postgres")
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@x:6543/postgres")
    fake = FakePgConn()
    monkeypatch.setattr(dbshim, "_pg_connect", lambda url: fake)
    conn = dbshim.connect(str(tmp_path / "guestbook-builder" / "run.db"))
    conn.execute("SELECT 1")
    sqls = [s for s, _ in fake.statements]
    assert any("CREATE SCHEMA" in s for s in sqls)                  # schema still created
    assert not any("INSERT INTO public.sf_runs" in s for s in sqls)  # but never registered

    fake2 = FakePgConn()
    monkeypatch.setattr(dbshim, "_pg_connect", lambda url: fake2)
    conn2 = dbshim.connect(str(tmp_path / "run-abcd1234" / "run.db"))
    conn2.execute("SELECT 1")
    assert any("INSERT INTO public.sf_runs" in s for s, _ in fake2.statements)


def test_ensure_refuses_path_shaped_run_id(monkeypatch, tmp_path):
    # Defense in depth: a run id that is clearly path/shell junk (contains a separator
    # or whitespace) must never reach CREATE SCHEMA, even bypassing the db-CLI guard.
    monkeypatch.setenv("SF_DB", "postgres")
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@x:6543/postgres")
    fake = FakePgConn()
    monkeypatch.setattr(dbshim, "_pg_connect", lambda url: fake)
    conn = dbshim.PgConn(fake, "/data/runs")
    with pytest.raises(ValueError):
        conn.execute("SELECT 1")
    assert not any("CREATE SCHEMA" in s for s, _ in fake.statements)
